### PR TITLE
Add up2date description of packetdrill grammar syntax

### PR DESCRIPTION
**Pull request by ligurio**
This commit adds description of grammar syntax used by packetdrill for
scripts.

Signed-off-by: Sergey Bronnikov <estetus@gmail.com>

### CODE REVIEW

**Comment by ligurio** [comment]
Neal (@nealcardwell), could you please review?

**Comment by ligurio** [comment]
Ping

**Comment by ligurio** [comment]
Updated syntax looks better than old one. Please look and compare:
https://gist.github.com/ligurio/e07b17f73a1d6b3c11ca708f92387560 and https://code.google.com/archive/p/packetdrill/wikis/Syntax.wiki

**Comment by ligurio** [comment]
Done.

**Comment by nealcardwell** [comment]
Thanks!

**Pull request merged**
